// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '1.9.22'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Ensure this version matches your Android Studio version
        classpath 'com.android.tools.build:gradle:8.2.2'
        // Note: I lowered this to 8.2.2 because 8.9.3 does not exist yet (it might be a typo).
        // If 8.9.3 works for you, change it back.
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        jcenter() // <--- This enables the "Old Store" for ancient libraries
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}