plugins {
    id 'com.android.application'
}

android {
	namespace "com.micromerger.ssms"
    compileSdkVersion 35

    defaultConfig {
        applicationId 'com.micromerger.ssms'
        minSdkVersion 21
        //noinspection ExpiringTargetSdkVersion,ExpiredTargetSdkVersion
        targetSdkVersion 35
        versionCode 35
        versionName "SSMS (2.91)"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        abortOnError false
    }

    buildFeatures {
        buildConfig = false
    }
}

//dependencies {
//    // TODO: dependencies
//    implementation 'androidx.appcompat:appcompat:1.7.1' // latest stable
//    implementation 'com.google.android.material:material:1.13.0'
//    implementation 'cn.pedant.sweetalert:library:1.3'
//    implementation 'com.google.android.gms:play-services-auth:21.4.0'
//    // Navigation Component
//    def nav_version = "2.7.2" // use latest stable
//    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
//    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
//    implementation 'com.jaredrummler:material-spinner:1.3.1'
//        // You may need both of these, try the first one first.
//    implementation 'org.checkerframework:checker-qual:3.52.0'
//    implementation 'com.android.support:support-media-compat:28.0.0'
//    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
//    implementation 'com.squareup.okhttp3:okhttp:5.3.2'
//    implementation 'com.squareup.okio:okio:3.16.4'
//    //noinspection GradleDependency
//    implementation "org.jetbrains.kotlin:kotlin-stdlib:$rootProject.ext.kotlin_version"
//    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2'
//    //noinspection Aligned16KB
//    implementation 'net.zetetic:android-database-sqlcipher:4.5.4'
////    implementation 'com.github.janishar:ParaCamera:1.0.1' // Check the exact format required by the repo owner
//    // or a more recent version
//}
dependencies {
    // --- CORE ANDROID ---
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$rootProject.ext.kotlin_version"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'

    // --- REPLACED LIBRARIES (Folders you DELETED) ---

    // Images (Replaces com/bumptech)
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    // Networking (Replaces com/squareup)
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.retrofit2:converter-moshi:2.9.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.squareup.moshi:moshi:1.15.1'

    // Animations (Replaces com/nineoldandroids)
    implementation 'com.nineoldandroids:library:2.4.0'

    // UI Widgets (Replaces com/pnikosis and com/jaredrummler)
    implementation 'com.pnikosis:materialish-progress:1.7'
    implementation 'com.jaredrummler:material-spinner:1.3.1'

    // --- EXISTING FOLDERS (Folders you KEPT/RESTORED) ---
    // No dependencies needed here because the code is in your src folder:
    // - AndroidNetworking
    // - ParaCamera
    // - SearchableSpinner
    // - SSL Utils
    // - Rockerhieu Adapter
    // - Integrated Biometrics

    // --- SECURITY ---
    implementation 'com.google.android.gms:play-services-auth:21.2.0'
    implementation 'net.zetetic:android-database-sqlcipher:4.5.4'

    // --- NAVIGATION ---
    def nav_version = "2.7.7"
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
}